
spring:
  application:
    name:
      UserCenter
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url : jdbc:mysql://localhost:3306/test

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
